# Generated by Django 4.0.4 on 2022-05-05 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='userid',
            field=models.IntegerField(auto_created=True, blank=True, null=True, unique=True, verbose_name='应聘者ID'),
        ),
    ]
