# Generated by Django 4.0.4 on 2022-05-05 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0002_alter_candidate_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='userid',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='应聘者ID'),
        ),
    ]
