# Generated by Django 4.0.4 on 2022-05-05 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0004_alter_candidate_test_score_of_general_ability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='first_learning_ability',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='学习能力得分'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='first_professional_competency',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='专业能力得分'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='first_score',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='初试分'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='paper_score',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='笔试分数'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='second_communication_ability',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='沟通能力得分'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='second_learning_ability',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='学习能力得分'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='second_pressure_score',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='抗压能力得分'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='second_professional_competency',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='专业能力得分'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='second_pursue_of_excellence',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='追求卓越得分'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='second_score',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='专业复试得分'),
        ),
    ]
