# Generated by Django 4.0.4 on 2022-05-05 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0003_alter_candidate_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='test_score_of_general_ability',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='综合能力测试分数'),
        ),
    ]
