# Generated by Django 4.0.4 on 2022-05-05 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0005_alter_candidate_first_learning_ability_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='create_date',
            new_name='created_date',
        ),
    ]
