#连接数据库
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/ssm
    driver-class-name: com.mysql.cj.jdbc.Driver
    # schema:
    # - classpath:createtabel.sql

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

