apiVersion: v1
kind: Pod
metadata:
  name: busy-pod

spec:
  containers:
  - image: busybox:latest
    name: busy
    imagePullPolicy: IfNotPresent
    env:
      - name: os
        value: linux
      - name: debug
        value: "on"
    command:
      - /bin/echo
    args:
      - "$(os),$(debug)"
status: {}