apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: vol-pod
  name: vol-pod
spec:
  volumes:
  - name: cm-vol
    configMap:
      name: info
  - name: secret-vol
    secret:
      secretName: user

  containers:
  - image: busybox
    name: vol-pod
    volumeMounts:
    - name: cm-vol
      mountPath: "/tmp/cm-vol"
    - name: secret-vol
      mountPath: "/tmp/secret-vol"
    command: ["/bin/sh", "-c", "sleep 3600"]
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
