# Generated by Django 4.0.4 on 2022-05-05 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_job_created_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-created_date'], 'verbose_name': '职位', 'verbose_name_plural': '职位'},
        ),
    ]
