server:
  port: 8080



spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456

# mybatis配置
mybatis:
  typeAliasesPackage: com.trendmicro.HelloWorld.bean
  mapperLocations: classpath\:mapper/*.xml
